### ISSUE TITLE
Chrome and Internet explorer works, but not on Firefox

### ISSUE THREAD

**Issue by lpalacin** [FriendsOfCake/cakephp-upload#349]
Hello,

Plug in  works perfectly in Chrome and Internet explorer browsers, but not in Firefox.

This is code:

```
$this->addBehavior('Josegonzalez/Upload.Upload', [
            'fitxer' => [
                'fields' => [
                    // if these fields or their defaults exist
                    // the values will be set.
                    'dir' => 'fitxer_dir', // defaults to `dir`
                    'size' => 'fitxer_size', // defaults to `size`
                    'type' => 'fitxer_type', // defaults to `type`
                ],
            ],
        ]);
```

[TdrsTable.txt](https://github.com/josegonzalez/cakephp-upload/files/88000/TdrsTable.txt)

```
<td><?=  $this->Html->link('Veure', '/' . $recipe->fitxer_dir . '' . $recipe->fitxer); ?></td>
```

[index.txt](https://github.com/josegonzalez/cakephp-upload/files/88002/index.txt)

Thank you

**Comment by josegonzalez** [comment]
What happens for Firefox browsers?

**Comment by lpalacin** [comment]
In Chrome and Explorer URL is 
http://localhost/tdr/webroot/files/Tdrs/fitxer/Read%20me.txt
All right


In Firefox URL is
http://localhost/tdr/webroot\files\Tdrs\fitxer\Read%20me.txt

See the \ bar instead the / bar
and display an "Object not found!" error

Thanh you for yours corrections

**Comment by josegonzalez** [comment]
Can you gist the html that is output to the browser in both chrome and firefox? This sounds like it's completely unrelated to the upload plugin, and rather something else...

**Comment by davidyell** [comment]
It'd also be helpful if you could further expand upon "not working". What have you tried? What are you expecting and what is happening?

**Comment by lpalacin** [comment]
Yes. 

![chrome](https://cloud.githubusercontent.com/assets/16499931/12296082/bd588626-ba05-11e5-96c3-bc1448f0b528.png)

In Chrome an Explorer when I push "Veure", browser outputs:
http://localhost/tdr/webroot/files/Tdrs/fitxer/Lazooterapia.pdf
and open correctly the pdf.
The source is:
td><a href="/tdr/webroot\files\Tdrs\fitxer\Lazooterapia.pdf">Veure</a></td>

In Firefox, browser outputs
http://localhost/tdr/webroot\files\Tdrs\fitxer\lazooterapia.pdf
The source is the same as Chrome:
td><a href="/tdr/webroot\files\Tdrs\fitxer\Lazooterapia.pdf">Veure</a></td>
but doesn't found the pdf file.

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/16499931/12296269/f593f4a2-ba06-11e5-8bcf-7782a41f88b5.png)

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/16499931/12296274/fd10bcce-ba06-11e5-872e-1dbbc3a20fef.png)


Thank you

**Comment by davidyell** [comment]
What does your view link look like? What's the actual PHP?

It should be something like `$this->Html->link('View', //etc`

**Comment by josegonzalez** [comment]
Can you gist the actual source contents as opposed to providing a pdf?

**Comment by lpalacin** [comment]
In view  cake code is

```
<td><?=  $this->Html->link('Veure', '/' . $recipe->fitxer_dir . '' . $recipe->fitxer); ?></td>
```
Both Chrome and Firefox, code source is

```
<td><a href="/tdr/webroot\files\Tdrs\fitxer\influenciadelallunaenelcreixementdelesplantes.pdf">Veure</a></td>
```
Chrome resolvs correctly but not Firefox.

**Comment by josegonzalez** [comment]
Okay so it looks like the `DIRECTORY_SEPARATOR` we are saving in the database doesn't work so well if you're on Windows. This works fine on a *nix systems, but not so great on windows since the DS is different than what urls use.

No good fix, since you'll break local file pathing if we use forward slashes. I hate windows.

You could try just doing `str_replace('\', '/', $recipe->fitxer_dir)`. I'll document this issue and come up with a configurable workaround.

**Comment by jorisvaesen** [comment]
If you want the dir (`\`) and the url (`/`) version saved to your database, you could use Virtual Fields and save the url based on the dir field and applying `str_replace('\', '/', $recipe->fitxer_dir)` there.

**Comment by Allan1** [comment]
Remember to escape the backslash, like so: str_replace('\\', '/', $this->fitxer_dir);
