### ISSUE TITLE
Existing files not delete on update

### ISSUE THREAD

**Issue by monsurhoq** [FriendsOfCake/cakephp-upload#423]
When I uploading a new file by editing record, new file upload successfully, but old file not removed.  I can't find any configuration for this feature.

**Comment by jorisvaesen** [comment]
What version of the plugin are you using?

**Comment by monsurhoq** [comment]
As per my comopser.json` "josegonzalez/cakephp-upload": "^3.6",`. I am using CakePHP 3.x

**Comment by jorisvaesen** [comment]
I don't think this plugin can handle this. To me it looks like you have 2 options: use nameCallback to overwrite your previous file with the new one, or delete the original file after a successful save in your code.
