### ISSUE TITLE
Size limit

### ISSUE THREAD

**Issue by michelef** [FriendsOfCake/cakephp-upload#431]
is there a size limit to the file.
I can upload small pdf less than 1MB but larger files fail with no error

**Comment by michelef** [comment]
I changed in the table to

     $this->addBehavior('Josegonzalez/Upload.Upload', [
            'attachment' => [
                'fields' => [
                     'dir' => 'attachments', // defaults to `dir`
                     'maxSize' => '102097152',
                 ],
            ],
        ]);

**Comment by michelef** [comment]
What I ended up doing is increase file size in php.ini
But still wandering why the above does not work
Thanks

**Comment by jorisvaesen** [comment]
Changing the option in the plugin does not change the php.ini setting. The setting in the plugin allows you to set the max file size lower than the php.ini's setting for a particular upload.

**Comment by michelef** [comment]
Thanks! I had misunderstood the function of the option.
Thanks also for a great plugin.
