### ISSUE TITLE
Examples: Changing the upload path dynamically

### ISSUE THREAD

**Issue by fietjeberlin** [FriendsOfCake/cakephp-upload#437]
Hi,

is there anywhere a example of "Changing the upload path dynamically"?

I don't understand it.

Thanks for help

mitch

**Comment by davidyell** [comment]
Which version of the plugin are you using?

**Comment by fietjeberlin** [comment]
I use 2.x

**Comment by fietjeberlin** [comment]
# Upload Plugin 2.0

**Comment by davidyell** [comment]
[Yes, you can find this in the documentation](http://cakephp-upload.readthedocs.io/en/2.x/examples.html#changing-the-upload-path-dynamically). Hope this helps.

**Comment by fietjeberlin** [comment]
thanks for the answer

do you have an example for me? 

my path is:  /upload/users/section/desk

in which _section_ and _desk_ are fields from the database.

**Comment by davidyell** [comment]
```php
$this->Behaviors->Upload->settings['field']['path'] = '{ROOT}upload{DS}users{DS}' . $section . '{DS}' . $desk . '{DS}';
```

**Comment by fietjeberlin** [comment]
it doesn't work.
if i put in the a controller

`public function beforeSave($options = array()) {
 		$this->Behaviors->Upload->settings['field']['path'] ='{ROOT}upload{DS}users{DS}' . $section . '{DS}' . $desk . '{DS}';    	
	}`

the file is saved in the /root/files/MODEL/FIELD/ID

why?


thanks

**Comment by davidyell** [comment]
You need to change the field to be your field name. I can't give you a copy and paste example, I'm sorry.

**Comment by miceg29** [comment]
Hi, everybody  
Someone have the same trouble  let me know what I'm doing wrong ?  this is my code 
/*Code like documentation It doesn't work */
	function beforeSave($options = array()) {
		parent::beforeSave($options);

		$newpath = '{ROOT}{DS}webroot{DS}files{DS}documents2{DS}';
		$this->Behaviors->Upload->settings['photo']['path'] = $newpath ;
		return true;
	}

/*Code with a Model  but If I  change like this */
	function beforeSave($options = array()) {
		parent::beforeSave($options);
		$newpath = '{ROOT}{DS}webroot{DS}files{DS}documents2{DS}';
		$this->Behaviors->Upload->settings[$this->alias]['photo']['path'] = $newpath ;
		return true;
	}

It's works but it made a folder like this in the next path
webroot/
            {ROOT}{DS}webroot{DS}files{DS}documents2{DS}

And It made a file like this 
webroot/{ROOT}{DS}webroot{DS}files{DS}documents2{DS}file.jpg
The plugin is wrong, let me know If I'm doing something wrong.

Thanks have a nice day.

**Comment by miceg29** [comment]
Hi every body again about my trouble I had the solution is this 

	function beforeSave($options = array()) {
		parent::beforeSave($options);
		$newpath = FILES . 'documents2'.DS ;
		$this->Behaviors->Upload->settings[$this->alias]['photo']['path'] = $newpath;
		return true;
	}

Where "photo" is your field that you want to chage it is so important to put the name Model or you can use the "$this->alias", see  you later I hope it could be help us.

**Comment by josegonzalez** [comment]
Ah yes, I believe we only interpolate the path when attaching the behavior, so you'd need to detach and re-attach the path in order to ensure that we use the correct replacements.

**Comment by BianchiniG** [comment]
Hi! The problem I am having with this is that when I change the upload path of the behavior, it changes for the entire system (Which is expected since it's a behavior, right?). 
The thing is, imagine there's someone saving a file right now, what if someone else on the system creates another instance of the table to make a save before the first save gets done? Wouldn't this mean that we've a race condition between those two? Or am I mistaken?

Thanks!
