### ISSUE TITLE
Rename file.

### ISSUE THREAD

**Issue by pogs17** [FriendsOfCake/cakephp-upload#438]
Hello guys,

I want to upload a file, renaming it before save.

How can i do this ?

Thanks in advance.

Pedro

**Comment by josegonzalez** [comment]
Were you able to figure this out, @pogs17 ? You can provide a `nameCallback` option to the behavior configuration that handles name manipulation.

**Comment by pogs17** [comment]
Thanks in advance Jose :)

**Comment by pogs17** [comment]
There's a option that i can set max file size ?

**Comment by josegonzalez** [comment]
Please read the documentation website, and very specifically read the [validation](https://cakephp-upload.readthedocs.io/en/latest/validation.html) documentation.
