### ISSUE TITLE
multiple upload not working

### ISSUE THREAD

**Issue by vicnoob** [FriendsOfCake/cakephp-upload#443]
Im trying to upload multiple files at the same time, but the result is just 1 file saved in the directory. Could you guide me, and 1 more question about the database, how can i add all records at once.

https://gist.github.com/vicnoob/33d4ff1065071c998e24ac39dffb02e0

**Comment by davidyell** [comment]
1. What version of the plugin are you using?
2. Are you using arrays for your upload fields in your forms?
3. Are you uploading multiple files to the same upload field or many files to many fields?

**Comment by vicnoob** [comment]
1. I have just installed the plugin this morning, so it probaly the lastest version.
2 & 3 I just follow the tutorial, trying to upload like 3 images at 1 times, all of related code is in the Gist already

**Comment by jorisvaesen** [comment]
This plugin doesn't support multiple files uploaded through one form field.
Fell free to do a PR to add this functionality.
