### ISSUE TITLE
rename upload file

### ISSUE THREAD

**Issue by weijihao** [FriendsOfCake/cakephp-upload#444]
`/vendor/josegonzalez/cakephp-upload/src/File/Path/Filename/DefaultTrait.php (line 19)
[
	(int) 0 => object(App\Model\Table\ArticlesTable) {

		'registryAlias' => 'Articles',
		'table' => 'articles',
		'alias' => 'Articles',
		'entityClass' => 'App\Model\Entity\Article',
		'associations' => [
			(int) 0 => 'categories',
			(int) 1 => 'users'
		],
		'behaviors' => [
			(int) 0 => 'Timestamp',
			(int) 1 => 'Upload'
		],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	},
	(int) 1 => 'abc',
	(int) 2 => object(App\Model\Table\ArticlesTable) {

		'registryAlias' => 'Articles',
		'table' => 'articles',
		'alias' => 'Articles',
		'entityClass' => 'App\Model\Entity\Article',
		'associations' => [
			(int) 0 => 'categories',
			(int) 1 => 'users'
		],
		'behaviors' => [
			(int) 0 => 'Timestamp',
			(int) 1 => 'Upload'
		],
		'defaultConnection' => 'default',
		'connectionName' => 'default'
	
	},
	(int) 3 => 'abc'
]`

**Comment by weijihao** [comment]
How can i do?

**Comment by Spriz** [comment]
@weijihao this is not a support forum :) 

Go check the existing issues, docs and go on the Cake slack channel to get help.

**Comment by davidyell** [comment]
Please see the `nameCallback` method in the documentation.

http://cakephp-upload.readthedocs.io/en/latest/configuration.html
