### ISSUE TITLE
Why cant I upload .pdf and .mp3 files ?

### ISSUE THREAD

**Issue by clementcrownrise** [FriendsOfCake/cakephp-upload#448]
Hi, please why is it that whenever I try to upload any file with the above format, i get an error and the upload doesnt work?

What do I need to do? thanks

**Comment by josegonzalez** [comment]
We don't block anyone from uploading any specific file types. Without knowing what error you get, we can't comment on whats going on either. You may wish to check if you have some validation rule enabled or if the file is too big to be uploaded because of php.ini settings.

**Comment by clementcrownrise** [comment]
The only error message I got was unable to add the record. I have not done any validation at all, is there any place in your plugin to specify extensions that should be acceptable ?

**Comment by josegonzalez** [comment]
We don't validate any extension types or anything unless your code requires that.
