### ISSUE TITLE
How to delete Attachment with polymorphic with correct path

### ISSUE THREAD

**Issue by macayer** [FriendsOfCake/cakephp-upload#451]
Hi,

Following that example:
http://cakephp-upload.readthedocs.io/en/2.x/polymorphic.html

Let's says we have a PostController (as the example above)
Add and Edit upload images in files/Image/attachment/[id]/... it works good.

I created AttachmentsController and created a delete function, so I can dynamically delete an attachment within my Post/Edit with an AjaxCall. But my problem is, the attachment will delete but not the image, because it is trying to delete with the path files/**attachment**/attachment/[id]. 

How can I specify to the attachment to delete with Image/attachment instead of attachment/attachment. 

Here's my delete code:

```php
public function admin_delete($id = null) {
		$this->Attachment->id = $id;

		//debug($this->Attachment); die();
		if (!$this->Attachment->exists()) {
			throw new NotFoundException(__('Invalid attachment'));
		}
		$this->request->allowMethod('get', 'post', 'delete');
		$this->Attachment->delete();
	}
```

Thx

**Comment by macayer** [comment]
@davidyell , @josegonzalez  any idea guys ? Thx

**Comment by davidyell** [comment]
I guess you'd need to dynamically update the path configuration in the behaviour before deleting the record.

Take a look at #437 this might give you some clues.

**Comment by macayer** [comment]
Thank you @davidyell  !

I added
```
public function beforeDelete($cascade = true)
    {
        $newpath = WWW_ROOT . 'files' . DS . 'image' . DS . 'attachment' . DS;
        $this->Behaviors->Upload->settings['Attachment']['attachment']['path'] =  $newpath;

        return true;
    }
```
So I can now delete dynamically delete a photo while using polymorphism
