### ISSUE TITLE
remove space from {microtime} field

### ISSUE THREAD

**Issue by anuj9196** [FriendsOfCake/cakephp-upload#458]
- [x] Bug

on using `{microtime}` in `path` the path contains a white space which sometimes causes problem in filesystem.

I am using this plugin to upload video files, although video files are uploading, the path contains white space
```
webroot/files/PostVideos/video_file/0.53236700 1498727983/file.mp4
```

**Comment by davidyell** [comment]
Closing in favour of pull request in #461
