### ISSUE TITLE
add primary key field in path while creating new entity

### ISSUE THREAD

**Issue by anuj9196** [FriendsOfCake/cakephp-upload#459]
- [x] Feature Request

Although there is `{primaryKey}` token to be use in path, it is not working for new entity (so, what is the use?)

Here is a CakePHP Image upload plugin by proffer : https://github.com/davidyell/CakePHP3-Proffer

This plugin use primary key to include in path where image file is being stored.

It will be better if this feature is added.

Because, everytime if I upload same file again, a new record is being created in table but file is replaced by new one. Which I don't want because may be new file is modified with same name which raise problem in finding old file

**Comment by josegonzalez** [comment]
The answer to this will always be "no". Using a primaryKey for on-disk storage is not going to be possible without a two-phase commit (which is what proffer does and what upload used to do). That is both error-prone and more complicated, so I removed the code. You'll get an exception now if you try to do that.

See [this comment](https://github.com/FriendsOfCake/cakephp-upload/issues/456#issuecomment-310250418) for more details.

**Comment by anuj9196** [comment]
So, what is the answer to my concern

> everytime if I upload same file again, a new record is being created in table but file is replaced by new one. Which I don't want because may be new file is modified with same name which raise problem in finding old file

**Comment by josegonzalez** [comment]
Do not use `{primaryKey}`. If you need something unique to the record, use the `{field-value:FIELDNAME}` replacement.

**Comment by davidyell** [comment]
Duplicate of #456

**Comment by anuj9196** [comment]
so, the `FIELDNAME` in `{field-valie:FIELDNAME}` will be replaced by `unique_id`?

**Comment by josegonzalez** [comment]
If you use a field called `unique_id` and set a value to it, then use `{field-value:unique_id}` in your path configuration, then the plugin will pull that value and use it as a replacement in the path.

Assuming you only set it when the entity is new, then this should work just fine as a replacement for `primaryKey`.
