### ISSUE TITLE
Problema al borrar thumbnail generado

### ISSUE THREAD

**Issue by fernaog** [FriendsOfCake/cakephp-upload#462]
Hola,

Siguiendo el ejemplo publicado en la documentación en este [link](http://cakephp-upload.readthedocs.io/en/latest/examples.html#advanced-example) todo funciona perfecto pero al momento de borrar el registro me esta borrando el original pero no el thumbnail. Alguna sugerencia? Gracias y saludos.

**Comment by josegonzalez** [comment]
Puedes mostrar lo que has escrito, y el version de cakephp-upload que tienes installado?

**Comment by fernaog** [comment]
Justo ahora hice un composer update y con la actualizacion mas reciente que hiciste quedó resuelto. Muchas gracias por la correción y por el plugin, me ha servido mucho. Saludos.

**Comment by josegonzalez** [comment]
De nada.
