### ISSUE TITLE
Associated model images are not deleting

### ISSUE THREAD

**Issue by manish-evolt** [FriendsOfCake/cakephp-upload#464]
Hi
I have two tables properties and propertyImages and they both have a relation. When i delete the property all the associated propertyImages records are deleted but propertyImages are not deleted. 
Please help

Thanks!

**Comment by davidyell** [comment]
My first thought would be that you'll need to enable callbacks, so the behavior can hook the delete.

In the table associations you'll need to add `'dependent' => true, 'cascadeCallbacks' => true`. [Read it in the book.](https://book.cakephp.org/3.0/en/orm/associations.html#hasmany-associations)
