### ISSUE TITLE
Upload field is empty when saving to database

### ISSUE THREAD

**Issue by filipecamargo10** [FriendsOfCake/cakephp-upload#469]
With this new version i try and not work.

## Model
```php
$this->addBehavior('Josegonzalez/Upload.Upload', [
            'photo',
]);
```

## Controller
```php
 if ($this->request->is('post')) {
            $document = $this->Documents->patchEntity($document, $this->request->getData());
            $document->user_id = $this->Auth->user('id');

            if ($this->Documents->save($document)) {
                $this->Flash->success(__('The document has been sended.'));
                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The document could not be sended. Please, try again.'));
}
```

## View
```php
 echo $this->Form->control('photo', ['type' => 'file', 'required' => 'true']);
```
I already put the form type as file.

The error is: 
`Error: SQLSTATE[HY000]: General error: 1364 Field 'photo' doesn't have a default value`

When i comment the behavior everything work's fine.
Anyone can help me ?

**Comment by Spriz** [comment]
That sure looks like an SQL error for your table field called "photo" :-)

**Comment by davidyell** [comment]
* So you are attaching the behaviour to the `DocumentsTable` right?
* The form type is `['type' => 'file']` ?
* You are validating the field is `notEmpty()` and `requirePresence()` in your `DocumentsTable` validation?

I'm not sure how your code is managing to save a Document with an empty `photo` field, but that's why you're seeing the error. So some PHP validation here would help catch this in PHP, where it will be easier to handle.

**Comment by filipecamargo10** [comment]
> So you are attaching the behaviour to the DocumentsTable right?
Right!
> The form type is ['type' => 'file']
Yes
> You are validating the field is notEmpty() and requirePresence() in your DocumentsTable validation?
Yes

If i comment the behavior works fine.

**Comment by filipecamargo10** [comment]
The problem has been fixed. Thanks guys.

**Comment by charlie4biz** [comment]
@filipecamargo10 wondering how you fixed the problem. Currently facing same issue.

**Comment by josegonzalez** [comment]
You need to ensure your form and field type are both `file`. This is almost always missed. Please do so, but if you have any other issues, file a separate bug. Thanks.
