### ISSUE TITLE
rename with table id

### ISSUE THREAD

**Issue by maikmarinho** [FriendsOfCake/cakephp-upload#473]
How to rename an image with table id

**Comment by josegonzalez** [comment]
Please see our documentation on naming your file during the upload process [here](https://cakephp-upload.readthedocs.io/en/latest/configuration.html).

**Comment by maikmarinho** [comment]
You can provide an example
From the documentation I did not see possibility
But with your skills.

**Comment by josegonzalez** [comment]
[Here](https://cakephp-upload.readthedocs.io/en/latest/examples.html) are examples in our documentation for configuring the behavior. Feel free to contribute an update.
