### ISSUE TITLE
composer took old file

### ISSUE THREAD

**Issue by mnishig** [FriendsOfCake/cakephp-upload#478]
I installed cakephp-upload with compose follwing command
`composer require josegonzalez/cakephp-upload`

Try to Example on document , but nameCallback occured error 

> Too few arguments to function App\Model\Table\UsersTable::App\Model\Table\{closure}(), 2 passed in /opt/yandex/ci-rec/sandbox/upload-ex/vendor/josegonzalez/cakephp-upload/src/File/Path/Filename/DefaultTrait.php on line 19 and exactly 5 expected 

and checked my installed file as bellow that seems like old.

・vendor/josegonzalez/cakephp-upload/src/File/Path/Filename/DefaultTrait.php

`
trait DefaultTrait
{
    /**
     * Returns the filename for the current field/data combination.
     * If a `nameCallback` is specified in settings, then that callable
     * will be invoked with the current upload data.
     *
     * @return string
     */
    public function filename()
    {
        $processor = Hash::get($this->settings, 'nameCallback', null);
        if (is_callable($processor)) {
            return $processor($this->data, $this->settings);
        }

        return $this->data['name'];
    }
}
`

**Comment by josegonzalez** [comment]
You probably have an older version of CakePHP and need to upgrade that as well to get a newer version of this plugin.

Closing as we don't control how composers dependency resolution works. I think you can use `conposer outdated` to see what you need to update
