### ISSUE TITLE
Saving correctly, but not uploading the image.

### ISSUE THREAD

**Issue by pmoraes** [FriendsOfCake/cakephp-upload#488]
Hey guys.

This is my first time using this plugin. 

I'm not sure if this is a bug or a mistake mine. Probably its a my mistake. 

What is happening. Its saving perfectly, the image name is in the photo field. Everything looks ok.

But the file is not uploaded to the folder. I'm using the basic example.

I have permissions to the folder. Anyone can know what is happening? 

This is behavior code 

`$this->addBehavior('Josegonzalez/Upload.Upload', [
            'photo' => []
        ]);`

**Comment by dreamingmind** [comment]
Two quick things to check,
1 - do the permissions allow writing to your destination folder
2 - is the picture too big. I remember my first attempts silently failing when the picture was past a size limit (can't remember the limit). I believe this limit was something set in php.ini, but again—a while ago; working from memory

**Comment by pmoraes** [comment]
both were checked and they are correct.

**Comment by pmoraes** [comment]
https://gist.github.com/pmoraes/a918bdfd818af7524f5c9179e5bd2e87

**Comment by josegonzalez** [comment]
Where do you expect the files to be saved on disk?

**Comment by pmoraes** [comment]
webroot/img/Tips/photos

**Comment by josegonzalez** [comment]
Why do you expect that path? Thats not the default configuration.

By default, we upload to:

```
webroot{DS}files{DS}{model}{DS}{field}{DS}
```

As specified by the `path` config option here: http://cakephp-upload.readthedocs.io/en/latest/configuration.html

**Comment by pmoraes** [comment]
yes.. this was totally my fault.. I didnt see this in the configuration. Thanks for your time.
