### ISSUE TITLE
incompatible with versions above 3.4. *

### ISSUE THREAD

**Issue by rederlo** [FriendsOfCake/cakephp-upload#492]
Call to undefined method Cake\Database\Schema\TableSchema::setColumnType()

**Comment by saeideng** [comment]
this method added since cake 3.5.0

**Comment by mentisy** [comment]
The cakephp/cakephp~3.4 constraint means it will upgrade up to (not including) 4.0, right? As of now, the latest version is 3.7.3, which means when I fork this repository, that is the version it will install when running composer install. 

When I then run tests in phpunit without altering anything, I will get an error as changes in the CakePHP core has changed. If I change composer.json to cakephp/cakephp:3.6, I get no such error.

The error I encounter is: 
`Uncaught InvalidArgumentException: Cannot convert value of type `string` to integer in X:\xampp\htdocs\cakephp-upload\vendor\cakephp\cakephp\src\Database\Type\IntegerType.php:64`

I'm not well versed in this yet, so let me know if I'm not thinking correctly.

**Comment by davidyell** [comment]
https://semver.mwl.be/#?package=cakephp%2Fcakephp&version=~3.4&minimum-stability=stable

So as you can see the constraint means 3.4.0 to any version above, but not a 4.x release. Perhaps the minimum constraint can be increased now? Any thoughts @josegonzalez

**Comment by ADmad** [comment]
@mentisy Mostly the plugin's test suite wasn't run after CakePHP 3.7 was released and needs some fix to account for changes in 3.7.
