### ISSUE TITLE
Uploading multiple files. Error Invalid data type, must be an array or \ArrayAccess instance.

### ISSUE THREAD

**Issue by VazLang** [FriendsOfCake/cakephp-upload#496]
Hello everyone i just started out using cakephp and php in general. First thank you Jose Gonzalez for the Plugin it really did help me a lot, while figuring out how to upload pictures. 

Multiple file upload works for me when only choosing two pictures, once i extend that to 3 or 4 i get this error message: Invalid data type, must be an array or \ArrayAccess instance.

Here is the part of the Table I am working on. Thanks in advance for your help.

```php
 public function initialize(array $config)
    {
        $this->setPrimaryKey('id');
        $this->belongsToMany('Tags');
        $this->addBehavior('Timestamp');

        $this->addBehavior('Josegonzalez/Upload.Upload', [
            //works with two
            'photolg',
            //stops working with 3rd and 4th
            //'photomd',
            //'photosm',
            'photo' => [
                'fields' => [
                    'dir' => 'photo_dir',
                ],
                'nameCallback' => function ($table, $entity, $data, $field, $settings) {
                    return strtolower($data['name']);
                },
                'transformer' =>  function ($table, $entity, $data, $field, $settings) {
                    $extension = pathinfo($data['name'], PATHINFO_EXTENSION);

                    // Store the thumbnail in a temporary file
                    $tmp = tempnam(sys_get_temp_dir(), 'upload') . '.' . $extension;

                    // Use the Imagine library to DO THE THING
                    $size = new \Imagine\Image\Box(100, 100);
                    $mode = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;
                    $imagine = new \Imagine\Gd\Imagine();

                    // Save that modified file to our temp file
                    $imagine->open($data['tmp_name'])
                        ->thumbnail($size, $mode)
                        ->save($tmp);

                    // Now return the original *and* the thumbnail
                    return [
                        $data['tmp_name'] => $data['name'],
                        $tmp => 'thumbnail-' . $data['name'],
                    ];
                },
                'deleteCallback' => function ($path, $entity, $field, $settings) {
                    // When deleting the entity, both the original and the thumbnail will be removed
                    // when keepFilesOnDelete is set to false
                    return [
                        $path . $entity->{$field},
                        $path . 'thumbnail-' . $entity->{$field}
                    ];
                },
                'keepFilesOnDelete' => false
            ]
        ]);
    }
```

**Comment by raul338** [comment]
That error may happen when the post size / file size is larger than configured.
You may have to tweak your php ini
```
post_max_size=20M
upload_max_filesize=20M
```

**Comment by VazLang** [comment]
Thanks for the suggestion. But it did not work even with those changes. I changed php.ini to
post_max_size=20M
upload_max_filesize=20M
 And even though the total upload size is 500kb i still get an error message.

**Comment by davidyell** [comment]
There are few things which I'd like to see for this issue.

1. What is the exact error message you get. It should include a file and line number. As this might be due to a callback you have. Invalid data type sounds to me like a PHP 7 type error.
2. Can you show us the php you are using to generate your form. As it might be the way you are sending your request data which is why you can't implement more than 2 uploads

**Comment by VazLang** [comment]
@davidyell Thank you for the Reply. 
Here is the Error massage I receive.
![bildschirmfoto 2018-10-18 um 10 54 48](https://user-images.githubusercontent.com/43746335/47142971-6b466a80-d2c4-11e8-8849-6254a4220590.png)

And here is the Form i create with the upload buttons. 

    <div class="container">
        <?= $this->Form->create($article, ['type' => 'file']); ?>
            <?php echo $this->Form->control('user_id', ['type' => 'hidden']); ?>

            <fieldset>
                <legend>Edit Article</legend>

                <div class="form-group">
                    <?= $this->Form->control(('title'), ['class'=> 'form-control']) ?>
                </div>

                <div class="form-group">
                    <?= $this->Form->control(('body'), ['class'=> 'form-control']) ?>
                </div>

                <div class="form-group">
                    <?= $this->Form->control(('tag_string'), ['class'=> 'form-control']) ?>
                </div>

                <div class="form-group">
                    <?= $this->Form->input('photo', ['type'=>'file']); ?>
                </div>

                
                <div class="form-group">
                    <?= $this->Form->input('photosm', ['type'=>'file']); ?>
                </div>

                <div class="form-group">
                    <?= $this->Form->input('photomd', ['type'=>'file']); ?>
                </div>

                
                <div class="form-group">
                    <?= $this->Form->input('photolg', ['type'=>'file']); ?>
                </div>

                

                <?= $this->Form->button(__('Save Article'), ['class'=> 'btn btn-primary']) ?>
            </fieldset>
        <?= $this->Form->end() ?>
    </div>

**Comment by davidyell** [comment]
So I think the problem is that your upload fields have no configuration.

```php
'photolg',
```

This is essentially `'photolg' => null` whereas the behaviour is expecting `must be an array or \ArrayAccess instance`.

So I believe the solution is to include the configuration for each upload field.

**Comment by VazLang** [comment]
@davidyell You are a magician, it now works like a charm. Thank you so much. The Table now looks like this: 

public function initialize(array $config)
    {
        $this->setPrimaryKey('id');
        $this->belongsToMany('Tags');
        $this->addBehavior('Timestamp');

        $this->addBehavior('Josegonzalez/Upload.Upload', [
            //works with two
            'photolg' => [
                'fields' => [
                    'dir' => 'photo_dir'
                ]
            ],
            //stops working with 3rd and 4th
            'photomd' => [
                'fields' => [
                    'dir' => 'photo_dir'
                ]
            ],
            'photosm' => [
                'fields' => [
                    'dir' => 'photo_dir'
                ]
            ],

            'photo' => [
                'fields' => [
                    'dir' => 'photo_dir',
                ],
                'nameCallback' => function ($table, $entity, $data, $field, $settings) {
                    return strtolower($data['name']);
                },
                'transformer' =>  function ($table, $entity, $data, $field, $settings) {
                    $extension = pathinfo($data['name'], PATHINFO_EXTENSION);

                    // Store the thumbnail in a temporary file
                    $tmp = tempnam(sys_get_temp_dir(), 'upload') . '.' . $extension;

                    // Use the Imagine library to DO THE THING
                    $size = new \Imagine\Image\Box(100, 100);
                    $mode = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;
                    $imagine = new \Imagine\Gd\Imagine();

                    // Save that modified file to our temp file
                    $imagine->open($data['tmp_name'])
                        ->thumbnail($size, $mode)
                        ->save($tmp);

                    // Now return the original *and* the thumbnail
                    return [
                        $data['tmp_name'] => $data['name'],
                        $tmp => 'thumbnail-' . $data['name'],
                    ];
                },
                'deleteCallback' => function ($path, $entity, $field, $settings) {
                    // When deleting the entity, both the original and the thumbnail will be removed
                    // when keepFilesOnDelete is set to false
                    return [
                        $path . $entity->{$field},
                        $path . 'thumbnail-' . $entity->{$field}
                    ];
                },
                'keepFilesOnDelete' => false
            ]
        ]);
    }

**Comment by davidyell** [comment]
Glad you've got it sorted 👍
