### ISSUE TITLE
How can I remove file (just remove from table) at patchEntity?

### ISSUE THREAD

**Issue by yousan** [FriendsOfCake/cakephp-upload#503]
Hi.
How can I remove a file at patchEntity?
The table has upload behavior.

```
public function patchEntity( EntityInterface $entity, array $data, array $options = [] ) {
   if ( empty($data['image'])) { // At a case with no image send at edit (update)
       // I want to clear Table::image column
   }
   return parent::patchEntity( $entity, $data, $options );
}

// Mistake was corrected, thank you for @dreamingmind 
```

**Comment by dreamingmind** [comment]
You should be able to `unset( )` any nodes you don't want in your data array or any properties you don't want in your entity.

Your example code mistakenly treats `entity` as an array by referencing `$entity['image']`. But the signature of your method states that `$entity` is an **EntityInterface** object. 

So, you probably want something more like this:

```
public function patchEntity( EntityInterface $entity, array $data, array $options = [] ) {
   if ( empty($data['image'])) { // At a case with no image send at edit (update)
       // I want to clear Table::image column
       unset($data['image']);
   }
   return parent::patchEntity( $entity, $data, $options );
}
```

**Comment by yousan** [comment]
@dreamingmind Thank you for your reply.

I tried `unset` and `empty string` and `null`.
But it has no effect, then I cannot clear the column.

**Comment by saeideng** [comment]
>I cannot clear the column.

from database ?

**Comment by saeideng** [comment]
when you delete a field from  $entity ( unset ) 
on your database is not effect 
with unset you are saying dont touch to this field

you should do like this in general 
```php
$entity = $this->Models->patchEntity($entity, $this->request->getData());
$entity->image = null;//for override the field 
```

**Comment by yousan** [comment]
@saeideng OK, should I have to set null after `patchEntity()`?
OK, I will try.

The patchEntity code is used at edit/create or somewhere else, so I try like belowing

```
public function patchEntity( EntityInterface $entity, array $data, array $options = [] ) {
	/** @var \App\Model\Entity\Report $report */
	$report = parent::patchEntity( $entity, $data, $options );
	$report->image = null;
	return $report;
}

**Comment by saeideng** [comment]
>The patchEntity code is used at edit/create or somewhere else

you should not override the patchEntity for this purpose 
what is  problem with this plugin ( upload behavior ) ?

**Comment by yousan** [comment]
@saeideng 
I am really thank your reply.
> what is problem with this plugin ( upload behavior ) ?
Well, I don't know the real reason. But I cannot clear DB column.

```
$model = $this->Somemodelsa->patchEntity( $report, $this->request->getData() );
$model->image = null;
$model->save();
```

But DB column is set by the filename.
Should I remove behavior or something?

**Comment by saeideng** [comment]
> Should I remove behavior or something?

with doing `$model->save();` , the `beforeSave()` from this behavior will execute
maybe problem is here 
yes if you need , you can disable it when  `image` is null , or in other cases that you want

**Comment by saeideng** [comment]
for remove a behavior 
https://book.cakephp.org/3.0/en/orm/behaviors.html#removing-loaded-behaviors

**Comment by yousan** [comment]
@saeideng 
Thank you for your reply ;)

> `$model->save();` , the `beforeSave()` from this behavior will execute maybe problem is here

I see, I understand. This great plugin hooks the stuff at `beforeSave`, OK.

So, the problem is a little bit complexed, because a ModelTable has multiple file column.
Let be `image_1`, `image_2` and `image_3` column.
`Edit` method sends `image_1` and to delete `image_2`.
I have to clear DB column for `image_2` but I need `image_1`.

At the beginning of this issue, I thought there are some methods to delete or clear properties to delete.
So, the way I should to implement is...

```
$model = $this->Somemodels->patchEntity( $report, $this->request->getData() );
$this->Somemodels->removeBehavior( 'Josegonzalez/Upload.Upload' );

// `addBehaviour` again at controller?
$this->Somemodels->addBehavior( 'Josegonzalez/Upload.Upload', [
'image_1' => ...
// 'image_2' // this should be commented out or `unset` to delete
'image_3' => ...
] );

$model->image_2 = null; // or unset, empty to clear DB column
$model->save();
```

**Comment by saeideng** [comment]
maybe this help you 
since the order of execute for `beforeSave` is first behavior and next table 
see : https://github.com/dereuromark/executionorder/blob/master/RESULTS.md#model-validate--save

probably you able to do like this on your table , it should overrides  the `$entity`
```php
//table
    public function beforeSave(Event $event, Entity $entity, ArrayObject $options)
    {
       if ( empty($field)) { // put your field name 
           $entity->set($field,null);
        }
   }
```

in this plugin ( behavior) there are 2 lines that I think you can not use above code in all cases
```php
                    $entity->set($field, $entity->getOriginal($field));
                    $entity->setDirty($field, false);
```
so probably you have to have a method on table class  to receive original values from controller 
```php

//table
    public function saveAndClearRemains($entity, $image_1,$image_2)
    {
       $this->image_1 =  $image_1;
       $this->image_2 =  $image_2;
      return save($entity);
   }
    public function beforeSave(Event $event, Entity $entity, ArrayObject $options)
    {
       if ( empty($this->image_1)) { // put your field name 
           $entity->set('image_1',null);
        }
   }

// controller

$entity = $this->Somemodels->patchEntity( $entity, $this->request->getData() );

$image_1 = $this->request->getData('image_1');
$this->Somemodels->saveAndClearRemains($entity,$image_1, ... );
```
I did not test above code, you can change it as you want
