### ISSUE TITLE
Does this accept urls instead of the files?

### ISSUE THREAD

**Issue by tgoeminne** [FriendsOfCake/cakephp-upload#517]
I was wonder if I can provide http://www.website.com/link-to-image.jpeg as the file to upload?

Maybe it was a different plugin that had this?

**Comment by ADmad** [comment]
This plugin doesn't accept urls instead of the files.

**Comment by tgoeminne** [comment]
Ok, it was another plugin that I tried sometime ago that had this... No plans on adding this somewhere?

**Comment by tgoeminne** [comment]
Ok I see it is the filegrabberBehaviour, but this got removed from the plugin? How can I use this from old plugin in the new one?

**Comment by tgoeminne** [comment]
@josegonzalez can you tell me how to implement filegrabberbehaviour?

**Comment by josegonzalez** [comment]
You would need to fake out the uploaded data in the same way normal file data gets uploaded.

If you need consulting beyond that, let me know via email and I can send you rates.
