### ISSUE TITLE
Add image validation method checking that exact dimensions match

### ISSUE THREAD

**Issue by mentisy** [FriendsOfCake/cakephp-upload#518]
##### Image Validation method `exactDimensions`

Currently you can check whether and image is below or above width and height, but no way to check if an image matches the exact dimensions. Granted, you can combine all of the existing validation to get there, but that means too much code.

_I will create a pull request for this feature request myself._

**Comment by jorisvaesen** [comment]
Closing since this is available through `Validation::imageSize()`
