### ISSUE TITLE
Enable deleteCallback to delete folders

### ISSUE THREAD

**Issue by marcheimendinger** [FriendsOfCake/cakephp-upload#523]
I use a `webroot{DS}files{DS}{time}{DS}` path. So for each file I create a folder with the current time. When I delete a file, I also want to delete the parent directory (`webroot{DS}files{DS}{time}`).

I tried by using a `deleteCallback` :
`return [$path . $entity->name, $path];`

Sadly it doesn't seem to work on folders but only on files. Would it be possible to add this feature to the `deleteCallback` method ?

**Comment by marcheimendinger** [comment]
Of course, but it would be neat to integrate this into the plugin so we can do it as described (juste add the folder dir into the deleteCallback returned array).

**Comment by davidyell** [comment]
Deletes are dangerous, especially if you delete a folder, so handling it in the users code would be more logical in my opinion.

**Comment by marcheimendinger** [comment]
For someone looking for something similar, this is how I'm doing it :
```php
public function afterDelete($event, $entity, $options)
    {
        $completeDir = WWW_ROOT . str_replace("webroot" . DS, "", $entity->dir);
        $folder = new Folder($completeDir);
        $files = $folder->find('.', false);
        if (empty($files)) {
            $folder->delete();
        }
    }
```
