### ISSUE TITLE
Unknown type "upload.file" error.

### ISSUE THREAD

**Issue by menshutin** [FriendsOfCake/cakephp-upload#546]
Plugin does not work with cakephp 4.1 and cakephp-upload 5.0.0-RC.

Stack trace:
CORE/src/Database/TypeFactory.php:78
Cake\Database\TypeFactory::build CORE/src/ORM/Marshaller.php:79
Cake\ORM\Marshaller->Cake\ORM\{closure} CORE/src/ORM/Marshaller.php:568
Cake\ORM\Marshaller->merge CORE/src/ORM/Table.php:2817
Cake\ORM\Table->patchEntity APP/Controller/CphotosController.php:55
App\Controller\CphotosController->add CORE/src/Controller/Controller.php:529
...
How can I fix this?

**Comment by ADmad** [comment]
You forgot to load the plugin.

**Comment by menshutin** [comment]
Sorry, my fault. It works.
