### ISSUE TITLE
Error when installing on CakePHP 4.1.6

### ISSUE THREAD

**Issue by felipebustillo** [FriendsOfCake/cakephp-upload#554]
When using:

``composer require josegonzalez/cakephp-upload´´

I get the following error:

Problem 1
    - Conclusion: remove cakephp/cakephp 4.1.6
    - Conclusion: don't install cakephp/cakephp 4.1.6
    - josegonzalez/cakephp-upload 4.0.0 requires cakephp/orm 3.*

How should I proceed?

**Comment by ADmad** [comment]
Try again. New v5.0 stable with Cake 4 compatibility has been released.
