### ISSUE TITLE
request to new tag on 3.x

### ISSUE THREAD

**Issue by saeideng** [FriendsOfCake/cakephp-upload#571]
hi , according to #552 and #557
we need pin `league/flysystem` to `1.x` version 
current fixes are for cake 3.5 + 
so could you add new tag for 3.x (this plugin) version ?
last version for this now is 3.8.1 ( compatible with  < cake 3.5 )

current version map:
5.x requires -> cake 4 +
4.x requires -> cake 3.5 +
3.x requires -> until cake 3.4

**Comment by ADmad** [comment]
Cake 3.4 is pretty old. Those still using it should either upgrade to a newer 3.x release or add `league/flysystem:^1.0` as direct dependency to the app which will prevent it's 2.x release from being pulled.

**Comment by saeideng** [comment]
OK, thanks
