### ISSUE TITLE
Class 'League\Flysystem\Adapter\Local' not found

### ISSUE THREAD

**Issue by enviniom** [FriendsOfCake/cakephp-upload#575]
Hi.
I'm having this error "Class 'League\Flysystem\Adapter\Local' not found" when I'm uploading a file.

Cakephp show me than this the line generating this error 

> 

public function getFilesystem(string $field, array $settings = []): FilesystemInterface
--
  | {
  | $adapter = new Local(Hash::get($settings, 'filesystem.root', ROOT . DS));
  | $adapter = Hash::get($settings, 'filesystem.adapter', $adapter);
  | if (is_callable($adapter)) {
  | $adapter = $adapter();
  | }

Anyone knows what do I have to do to solve it?

**Comment by davidyell** [comment]
As the plugin include this library in the composer file, I would guess that you've either not installed using Composer, or your autoload is broken somehow.

Try either re-installing with `composer install`, or re-generating the autoload with `composer dumpautoload`

**Comment by enviniom** [comment]
I really apreciate your help, reinstaling works. Thank you so much.
