### ISSUE TITLE
cake-5 branch not installable

### ISSUE THREAD

**Issue by passchn** [FriendsOfCake/cakephp-upload#595]
When trying to require the plugin in the cake-5 branch, there is an issue with cakephp/orm: 

````
  Problem 1
    - Root composer.json requires cakephp/cakephp 5.x-dev -> satisfiable by cakephp/cakephp[5.x-dev].
    - josegonzalez/cakephp-upload dev-cake-5 requires cakephp/orm ^4.0.2 -> satisfiable by cakephp/orm[4.0.2, ..., 4.x-dev].
    - Only one of these can be installed: cakephp/orm[4.0.2, ..., 4.x-dev], cakephp/cakephp[5.x-dev]. cakephp/cakephp replaces cakephp/orm and thus cannot coexist with it.
    - Root composer.json requires josegonzalez/cakephp-upload cake-5-dev -> satisfiable by josegonzalez/cakephp-upload[dev-cake-5].
````

Related issue in another plugin: https://github.com/brandcom/cakephp-assets/issues/11

**Comment by LordSimal** [comment]
This has been fixed via https://github.com/FriendsOfCake/cakephp-upload/pull/593

**Comment by zoghal** [comment]
this branch!   not installable again
```
  Problem 1
    - Root composer.json requires josegonzalez/cakephp-upload dev-cake-5 -> satisfiable by josegonzalez/cakephp-upload[dev-cake-5].
    - josegonzalez/cakephp-upload dev-cake-5 requires cakephp/orm 5.x-dev -> found cakephp/orm[5.x-dev] but it does not match your minimum-stability.
```

**Comment by passchn** [comment]
@zoghal What is your minimum stability in composer.json? This seems to be the problem it seems like?

**Comment by zoghal** [comment]
> @zoghal What is your minimum stability in composer.json? This seems to be the problem it seems like?

I encountered this error when I just wanted to test version 5.
So my minimum stability in composer.json, is the one defined here: https://github.com/cakephp/app/blob/5.x/composer.json

**Comment by passchn** [comment]
In relation to https://github.com/brandcom/cakephp-assets/issues/11 - when will a release for cakephp 5 come out? :)
